### ISSUE TITLE
mvn install giving me IllegalStateException due to higher percentage of invalid records

### ISSUE THREAD

**Issue by riaz** [yahoo/covid-19-api#9]
$mvn clean install 

[WARNING] 
java.lang.IllegalStateException: Percentage of Invalid Record 7.26158 did not meet the threshold 5.00000
	at com.yahoo.covid19.database.DatabaseBuilder.validateDbRecordCount(DatabaseBuilder.java:436)
	at com.yahoo.covid19.database.DatabaseBuilder.build(DatabaseBuilder.java:283)
	at com.yahoo.covid19.database.DataFetcher.fetchDataAndProcess(DataFetcher.java:46)
	at com.yahoo.covid19.database.DatabaseBuilder.main(DatabaseBuilder.java:496)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
	at java.lang.Thread.run(Thread.java:748)

**Comment by aklish** [comment]
Our build fails if the data quality drops below some threshold.  

From the data repo:
this is probably due to zipcode and UK boroughs being included
"I am not sure how you determine validity zipcodes have no wikiId
region type for zipcode is “PostalZip” for boroughs it is “TertiaryAdminArea”

We are looking into it.

**Comment by aklish** [comment]
You can bump the threshold until we fix the DQ checks or the data.

**Comment by riaz** [comment]
ok cool, thank you for letting me know
